version: '3.8'

services:
  aphrodite-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: aphrodite-engine-${MODEL_ID:-gpt2}
    container_name: aphrodite-${MODEL_ID:-gpt2}-${USER_ID}
    ports:
      - "${HOST_PORT:-2242}:2242"
    environment:
      - MODEL_ID=${MODEL_ID:-gpt2}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - APHRODITE_OPENVINO_KVCACHE_SPACE=8
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  huggingface-cache:
    external: false